title: Vue
description: Nuxt is a framework for full-stack web apps and websites. Learn how to set it up with Sentry.
sdk: sentry.javascript.nuxt
sidebar_order: 4
categories:
  - javascript
  - browser
  - server